version: '3.8'
services:

  api:
    build:
      context: ./api
      target: dev
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./api:/var/www/html
      - ./api/.env.dev:/var/www/html/.env
    ports:
      - 8000:80
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - api-network
    depends_on:
      - mysql

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - 8080:8080
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - api-network
    depends_on:
      - api

  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "laravel"
      MYSQL_PASSWORD: "FhgVoFuOrWspc3TgBIA2K4dZGuJTPwSYBoLnNckcaxy"
      MYSQL_DATABASE: "laravel"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3906:3306
    volumes:
      - 'mysql8:/var/lib/mysql'
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
volumes:
  mysql8:
    driver: local